try:
    print(a)
except:
    print('erro')